apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config
  namespace: project
data:
  IMAGE_URL: "https://picsum.photos/800/400"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: project
data:
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres-svc
  POSTGRES_PORT: "5432"
