apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/configmap.yaml
  - manifests/cronjob.yaml
  - manifests/pvc.yaml
  - manifests/deployment.yaml
  - manifests/gateway-route.yaml
  - manifests/secret.yaml
  - manifests/postgres.yaml
  - manifests/broadcaster.yaml
