apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-staging

resources:
- ../../base

patches:
- path: broadcaster-json.yaml
  target:
    group: apps
    kind: Deployment
    name: broadcaster
    version: v1

images:
- name: broadcaster-image
  newName: gedionkip/k8s-submissions
  newTag: broadcaster-2f215959948faf79e7bdd452e392d8910728dfba
- name: curlimages/curl
  newTag: latest
- name: postgres
  newTag: "17"
- name: todo-app
  newName: gedionkip/k8s-submissions
  newTag: todo-app-2f215959948faf79e7bdd452e392d8910728dfba
- name: todo-backend
  newName: gedionkip/k8s-submissions
  newTag: todo-backend-2f215959948faf79e7bdd452e392d8910728dfba
