apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-prod

resources:
- ../../base
- backup-cronjob.yaml

images:
- name: broadcaster-image
  newName: gedionkip/k8s-submissions
  newTag: broadcaster-50ab88c1efec1736bd6f038382de5e415046de95
- name: curlimages/curl
  newTag: latest
- name: postgres
  newTag: "17"
- name: todo-app
  newName: gedionkip/k8s-submissions
  newTag: todo-app-50ab88c1efec1736bd6f038382de5e415046de95
- name: todo-backend
  newName: gedionkip/k8s-submissions
  newTag: todo-backend-50ab88c1efec1736bd6f038382de5e415046de95
