apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-prod

resources:
- ../../base
- backup-cronjob.yaml

images:
- name: broadcaster-image
  newName: gedionkip/k8s-submissions
  newTag: broadcaster-c5ab72cbaf69b6f47a41cf7f9cda29fbaa13af75
- name: curlimages/curl
  newTag: latest
- name: postgres
  newTag: "17"
- name: todo-app
  newName: gedionkip/k8s-submissions
  newTag: todo-app-c5ab72cbaf69b6f47a41cf7f9cda29fbaa13af75
- name: todo-backend
  newName: gedionkip/k8s-submissions
  newTag: todo-backend-c5ab72cbaf69b6f47a41cf7f9cda29fbaa13af75
