apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-prod

resources:
- ../../base
- backup-cronjob.yaml

images:
- name: broadcaster-image
  newName: gedionkip/k8s-submissions
  newTag: broadcaster-cd306a0b2e5a387e3a85bfe1ab27f72488770ada
- name: curlimages/curl
  newTag: latest
- name: postgres
  newTag: "17"
- name: todo-app
  newName: gedionkip/k8s-submissions
  newTag: todo-app-cd306a0b2e5a387e3a85bfe1ab27f72488770ada
- name: todo-backend
  newName: gedionkip/k8s-submissions
  newTag: todo-backend-cd306a0b2e5a387e3a85bfe1ab27f72488770ada
