apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-prod

resources:
- ../../base
- backup-cronjob.yaml

images:
- name: broadcaster-image
  newName: gedionkip/k8s-submissions
  newTag: broadcaster-36530d2f15c9082dce599e22373286b1c8dbdf0d
- name: curlimages/curl
  newTag: latest
- name: postgres
  newTag: "17"
- name: todo-app
  newName: gedionkip/k8s-submissions
  newTag: todo-app-36530d2f15c9082dce599e22373286b1c8dbdf0d
- name: todo-backend
  newName: gedionkip/k8s-submissions
  newTag: todo-backend-36530d2f15c9082dce599e22373286b1c8dbdf0d
