apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: project
stringData:
  POSTGRES_PASSWORD: StrongP@ssw0rd
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
  namespace: project
stringData:
  BROADCASTER_URL: https://discord.com/api/webhooks/1464513767034454100/bMS2ZbYEP_eRpHRUw_AiYzhEcLtzY6O4MShT3IIxb09IQI3U8zolQAHoDi1cc56OIjbJ